---
- name: install PHP
  shell: |
    sudo apt install software-properties-common
    sudo add-apt-repository ppa:ondrej/php -y
    sudo apt update
    sudo apt install -y php7.4
    php -v
    sudo apt-cache search php7*
    sudo apt install -y php7.4-fpm php7.4-mysql php7.4-curl php7.4-json php7.4-cgi php7.4-xsl php7.4-mbstring php7.4-opcache php7.4-gd php7.4-pgsql php7.4-intl php7.4-bcmath php7.4-soap
  tags: "install-php"
#  notify: start php

