- name: Setup Nginx and PHP
  hosts: "{{ hostname }}"
  gather_facts: yes
  become: yes
  
  roles:
    - { role: nginx, tags: ["webserver"] }
    - { role: php, tags: ["php"] }
    - { role: config-firewall, tags: ["firewall"] }
