---
# tasks file for ansible-role-nginx
- include: install
  tags:
    - install
- include: config
  tags:
    - config

- name: Create virtual host
  include: vhost.yml vhost={{ item }}
  with_items:
    - "{{ vhost01 }}"
    - "{{ vhost02 }}" 