---
- hosts: group-hosts
  gather_facts: yes
  become: yes
  #  pre_tasks:
  #  - name: 'install python'
  #  raw: sudo apt-get update && sudo apt-get -y install python3
  tasks:
  - name: ping
    action: ping
  - name: show user
    shell: |
      pwd
      whoami
    tags: "show-user"
    # - name: "tao file"
    #command: touch /home/phuvt/file1.txt
    #ignore_errors: yes
    #become: yes
    #  - name: install PHP
    #    shell: |
    #  sudo apt install software-properties-common
    #  sudo add-apt-repository ppa:ondrej/php -y
    #  sudo apt update
    #  sudo apt install -y php7.4
    #  php -v
    #  sudo apt-cache search php7*
    #  sudo apt install -y php7.4-fpm php7.4-mysql php7.4-curl php7.4-json php7.4-cgi php7.4-xsl php7.4-mbstring php7.4-opcache php7.4-gd php7.4-pgsql php7.4-intl php7.4-bcmath php7.4-soap
    #tags: "install-php"
    # become: yes
    #  - name: install nginx
    #apt:
    #  name: nginx
    # state: absent
      #    notify: start nginx
      #handlers:
      #- name: start nginx
      #systemd:
      # name: nginx
      #state: started      
      #enabled: true
      #  - name: start nginx
      #    shell: systemctl start nginx
    #systemctl enable nginx
      #post_tasks:
      #- name: "check nginx status"
      #shell: "{{item}}"
      # with_items:
      # - mkdir /home/phuvt/folder1
      #- cd /home/phuvt/folder1 && touch file2.txt
      # - echo user_phuvt > /home/phuvt/folder1/file2.txt
      # becom_user: phuvt
      # ignore_errors: yes
  roles:
  - role: ansible-role-nginx
  - role: php

